language: java

jdk:
  - openjdk14

sudo: false

install: true
script:
  - mvn install
services:
  - postgresql

before_install:
  - psql -c "CREATE DATABASE tracker_storage;" -U postgres
  - psql -c "CREATE DATABASE web_storage;" -U postgres
  - psql -c "CREATE DATABASE store_db;" -U postgres
  - psql -c "CREATE DATABASE shop_db;" -U postgres
  - psql -c "CREATE DATABASE offers_db;" -U postgres
  - psql -c "CREATE DATABASE cinema;" -U postgres
  - psql -c "CREATE DATABASE service;" -U postgres

env:
  global:
    - CODECOV_TOKEN="3884bd6d-aa52-47b5-8704-d12bcc0c3882"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - zubovvp@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always