# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
jdk:
  - openjdk12
sudo: false
install: true
script:
  - mvn install
services:
  - postgresql

before_install:
  - psql -c "CREATE DATABASE tracker_storage;" -U postgres
  - psql -c "CREATE DATABASE web_storage;" -U postgres
  - psql -c "CREATE DATABASE store_db;" -U postgres
  - psql -c "CREATE DATABASE shop_db;" -U postgres
  - psql -c "CREATE DATABASE offers_db;" -U postgres
  - psql -c "CREATE DATABASE cinema;" -U postgres
  - psql -c "CREATE DATABASE service;" -U postgres



# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - zubovvp@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always